% Fast end-to-end smoke test for the imported Si8 ISDF case.
% It keeps the source case's Gamma/static/QRCP setup while reducing the
% band window and rank ratios so it is suitable for automated validation.

clc;
clear;
rng(0, 'twister');
KSSOLV_startup;
[sys, options, syms] = read_qe_gw('.\\example\\qe_data\\si8', 1);
[sys, options] = gw_setup(sys, options);

eps = struct('nbnd', 48, 'nv', options.nv, 'nc', 48 - options.nv, ...
    'freq_dep', 0, 'cutoff', 15, 'coul_cut', 'spherical_truncation', ...
    'coul_cutoff', 5, 'save_mem', false, 'use_gpu', false, ...
    'precompute_wav', false);
eps.isdf = struct('enable', true, 'algorithm', 'reduced_basis', ...
    'output', 'screened_w', 'sample_method', 'qrcp_randomized', ...
    'rank_ratio_vc', 2, 'adaptive_rank_enable', false, ...
    'seed', 0, 'reduced_solver', 'cauchy');
eps = epsilon(sys, options, syms, eps);

sig = struct('nbnd', 48, 'ndiag_min', 1, 'ndiag_max', 2, ...
    'freq_dep', 0, 'coul_cut', 'spherical_truncation', ...
    'coul_cutoff', 5, 'no_symmetries_q_grid', false, ...
    'exact_static_ch', false, 'use_gpu', false, 'precompute_wav', false);
sig.isdf = struct('enable', true, 'algorithm', 'reduced_basis', ...
    'sample_method', 'qrcp_randomized', 'rank_ratio_nn', 2, ...
    'rank_ratio_vn', 3, 'exchange_space', 'vn', 'reuse_nn_for_vn', false, ...
    'adaptive_rank_enable', false, 'global_nn_space', true, ...
    'global_vn_space', true, ...
    'seed', 0, 'reduced_solver', 'cauchy');
sig = sigma(eps, sig, sys, options, syms);

assert(all(isfinite(sig.sig(:))), 'Si8 smoke test produced non-finite sigma.');
fprintf('SI8_ISDF_SMOKE_OK: %d diagonal bands.\n', size(sig.sig, 1));
