script_dir = fileparts(mfilename('fullpath'));
repo_root = fileparts(fileparts(fileparts(script_dir)));
epsilon_file = fullfile(repo_root, 'src', 'GW', 'epsilon', 'epsilon.m');
source = fileread(epsilon_file);

assert(contains(source, 'ops = epsilon_ops(ctx);'));
assert(contains(source, 'contribution = ops.evaluate(block);'));
assert(contains(source, 'acc = ops.accumulate(acc, contribution, block);'));
assert(~contains(source, 'use_isdf = isfield'), ...
    'epsilon.m must not resolve ISDF mode inside its main loop.');
assert(~contains(source, 'isdf_epsilon_reduced_basis'));
assert(isempty(regexp(source, ...
    'isdf_epsilon_reduced_basis\([^;]+;\s*return', 'once')));
assert(exist(fullfile(repo_root, 'src', 'GW', 'ISDF', ...
    'isdf_epsilon_reduced_basis.m'), 'file') == 0);

ops_file = fullfile(repo_root, 'src', 'GW', 'epsilon', 'epsilon_ops.m');
ops_source = fileread(ops_file);
init_reduced_file = fullfile(repo_root, 'src', 'GW', 'epsilon', ...
    'private', 'epsilon_reduced_init.m');
assert(exist(init_reduced_file, 'file') == 2, ...
    'Could not locate epsilon_reduced_init private helper.');
init_reduced = fileread(init_reduced_file);
assert(contains(ops_source, 'epsilon_reduced_init'), ...
    'epsilon_ops.m must route reduced initialization to its private helper.');
assert(~contains(init_reduced, '.output') && ...
    ~contains(init_reduced, 'lower(') && ...
    ~contains(init_reduced, 'strcmp('), ...
    'Reduced output must be parsed once during epsilon_ops construction.');

accumulate_position = strfind(source, ...
    'acc = ops.accumulate(acc, contribution, block);');
progress_position = strfind(source, ...
    'print_progress(current_epsilon_work, total_epsilon_work, ...');
accumulate_position = accumulate_position(1);
progress_position = progress_position(find( ...
    progress_position > accumulate_position, 1, 'first'));
assert(~isempty(progress_position), ...
    'Could not locate epsilon block progress after accumulation.');
assert(accumulate_position < progress_position, ...
    'Epsilon progress must report completed block work.');
assert(contains(source, 'epsilon_task = ''epsilon_main'';'), ...
    'Epsilon progress must use one global task for elapsed/ETA.');
assert(contains(source, 'epsilon_block_work = max(1, nvbands * ncbands);'), ...
    'Epsilon progress must account for band-pair work.');

fprintf('ISDF shared epsilon loop structure test passed.\n');
